import { type Candidate } from "@/types/candidate";

export const candidates: Candidate[] = [
  {
    id: "1",
    name: "Sagar",
    title: "Lead Senior Frontend Developer",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "6+ Years",
    availability: "Immediately",
    summary:
      "Experienced Lead Senior Frontend Developer with over 6 years of expertise in creating high-performance, scalable, and user-centric web applications. Specialized in React, TypeScript, and modern frontend technologies with a deep understanding of web performance, clean code practices, and UI/UX principles. Strong background in leading teams, architecting solutions, and optimizing complex applications for both speed and maintainability.",
    skills: [
      {
        category: "Frontend Development",
        items: [
          "React",
          "Next.js",
          "TypeScript",
          "Redux / Redux Toolkit",
          "Tailwind CSS",
          "GraphQL",
          "Material UI",
          "Styled Components",
          "Web Accessibility",
          "Responsive Design",
          "Atomic Design Principles",
        ],
      },
      {
        category: "Performance Optimization",
        items: [
          "Code Splitting",
          "Lazy Loading",
          "Tree Shaking",
          "Service Workers",
          "Performance Auditing (Lighthouse)",
          "SEO Optimization",
          "Critical Rendering Path Optimization",
        ],
      },
      {
        category: "Leadership & Collaboration",
        items: [
          "Team Leadership",
          "Agile & Scrum Methodologies",
          "Code Reviews & Mentorship",
          "Stakeholder Management",
          "Cross-functional Collaboration",
          "System Design & Architecture",
        ],
      },
      {
        category: "DevOps & CI/CD (Familiar)",
        items: [
          "Git",
          "Docker",
          "AWS (EC2, S3, Lambda)",
          "CI/CD Pipelines",
          "Terraform",
          "Jenkins",
        ],
      },
    ],
    workExperience: [
      {
        title: "Lead Senior Frontend Developer",
        company: "TechCorp Inc.",
        projectTitle: "LMS Portal",
        achievements: [
          "Led the front-end development of a large-scale Learning Management System (LMS), improving user engagement and accessibility.",
          "Architected and implemented reusable component libraries with a focus on scalability and maintainability.",
          "Optimized front-end performance by utilizing lazy loading, code splitting, and efficient state management (Redux).",
          "Guided a team of frontend developers, conducted code reviews, and mentored junior developers to elevate the overall team’s performance.",
          "Worked closely with UX/UI designers to implement responsive, high-quality user interfaces, maintaining consistency across platforms.",
        ],
        technologies: [
          "React",
          "Redux",
          "Next.js",
          "TypeScript",
          "Tailwind CSS",
          "Material UI",
          "SASS",
          "GraphQL",
          "REST APIs",
          "Web Accessibility",
        ],
      },
      {
        title: "Senior Frontend Developer",
        company: "TechCorp Inc.",
        projectTitle: "Telecom Marketplace",
        achievements: [
          "Led the frontend development of an e-commerce platform, enabling a seamless user experience for B2B telecom services.",
          "Optimized complex web pages for performance, reducing load times by over 40%.",
          "Collaborated with backend engineers to design and implement REST APIs, improving data exchange efficiency.",
          "Mentored junior developers and conducted knowledge-sharing sessions on modern web development practices.",
        ],
        technologies: [
          "React",
          "Next.js",
          "Redux",
          "Tailwind CSS",
          "GraphQL",
          "HTML5",
          "CSS3",
          "JavaScript",
          "AWS",
          "REST APIs",
        ],
      },
      {
        title: "Frontend Engineer",
        company: "TechCorp Inc.",
        projectTitle: "Talent Engagement",
        achievements: [
          "Built and optimized the frontend of a talent engagement platform, significantly improving the user experience and streamlining workflows.",
          "Integrated complex UI components and managed state across large-scale applications using React and Redux.",
          "Ensured application responsiveness across multiple devices, adhering to modern frontend best practices and mobile-first design.",
          "Created reusable UI components, reducing development time for future features.",
        ],
        technologies: [
          "React",
          "Redux",
          "Next.js",
          "HTML5",
          "CSS3",
          "JavaScript",
          "SASS",
          "Bootstrap",
          "Node.js",
        ],
      },
      {
        title: "Senior UI Developer",
        company: "TechCorp Inc.",
        projectTitle: "Online Dating & Chat Application",
        achievements: [
          "Led front-end development and implemented React-based UI for a real-time messaging and dating application with over 100,000 active users.",
          "Optimized the user interface for speed and responsiveness, achieving an average performance score of 90+ on Google Lighthouse.",
          "Worked on implementing WebSocket and state management using React Query, ensuring smooth and real-time communication for users.",
        ],
        technologies: [
          "React",
          "Next.js",
          "Redux",
          "React Query",
          "Tailwind CSS",
          "Web Socket",
          "AWS",
          "GraphQL",
        ],
      },
      {
        title: "Frontend Architect",
        company: "xyz",
        projectTitle: "ChatConcept",
        achievements: [
          "Designed and architected the frontend of a comprehensive chat application, leading both the technical direction and the frontend team.",
          "Implemented advanced features such as real-time messaging, file uploads with AWS S3, and seamless socket integration using Socket.IO.",
          "Conducted architectural reviews and made key decisions on frontend structure, ensuring long-term maintainability and scalability.",
        ],
        technologies: [
          "React",
          "Redux",
          "TypeScript",
          "Next.js",
          "Socket.IO",
          "MongoDB",
          "AWS S3",
          "REST API",
          "Express",
        ],
      },
      {
        title: "Senior Frontend Developer",
        company: "xyz",
        projectTitle: "AV Compliance",
        achievements: [
          "Developed the frontend of a compliance tracking application for regulatory requirements with custom reporting features.",
          "Integrated OCR system to parse and extract text from uploaded documents, providing automated data input for users.",
          "Ensured application compliance with WCAG standards to cater to users with disabilities.",
        ],
        technologies: [
          "React",
          "Next.js",
          "TypeScript",
          "GraphQL",
          "D3.js",
          "CSS3",
          "AntD",
          "Redis",
          "REST APIs",
        ],
      },
      {
        title: "Lead Frontend Developer",
        company: "xyz",
        projectTitle: "AV Biz App",
        achievements: [
          "Led the development of a cross-platform mobile application for booking AV services, streamlining user booking experiences.",
          "Integrated Firebase for real-time database syncing and Cloud Functions for seamless backend communication.",
          "Collaborated with UX/UI designers to ensure a polished and accessible mobile interface.",
        ],
        technologies: [
          "React Native",
          "Firebase",
          "JavaScript",
          "Expo",
          "MomentJS",
          "AntD",
        ],
      },
      {
        title: "Senior Frontend Developer",
        company: "xyz",
        projectTitle: "LMS Desktop App",
        achievements: [
          "Developed a desktop application using ElectronJS to manage learning resources and administrative workflows.",
          "Integrated real-time data handling using Redux and managed complex interactions between frontend and backend systems.",
        ],
        technologies: [
          "Next.js",
          "Redux",
          "ElectronJS",
          "HTML5",
          "JavaScript",
          "SCSS",
        ],
      },
    ],
    education: [
      {
        degree: "M.S. Computer Science",
        description:
          "Focus on Distributed Systems, Machine Learning, and Cloud Computing",
      },
    ],
  },
  {
    id: "2",
    name: "Apurva",
    title: "Front-End Developer",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "4+ Years",
    availability: "immediately",
    summary:
      "4+ years of hands-on experience in front-end development, proficient in using JavaScript, React JS, and Next JS. Extensive experience in creating user-facing features, building reusable components, and optimizing applications for speed and scalability. Proven ability to work independently, take initiative, and collaborate effectively within diverse team environments. Recognized for a meticulous and detail-oriented approach, excelling in delivering high-quality code and improving development efficiency.",
    skills: [
      {
        category: "Frontend Development",
        items: [
          "JavaScript",
          "TypeScript",
          "React JS",
          "Next JS",
          "Tailwind CSS",
          "Redux",
          "GraphQL",
        ],
      },
      {
        category: "Performance Optimization",
        items: [
          "Code Splitting",
          "Lazy Loading",
          "Tree Shaking",
          "Performance Auditing (Lighthouse)",
        ],
      },
      {
        category: "API Integration",
        items: ["REST APIs", "GraphQL", "Web Socket"],
      },
      {
        category: "UI/UX Design",
        items: [
          "Responsive Design",
          "User Interface Design",
          "Cross-browser Compatibility",
        ],
      },
    ],
    workExperience: [
      {
        title:
          "Frontend Developer - Web Application for RV and Caravan Rentals",
        company: "Freelance/Contract",
        projectTitle: "2023 - Present",
        achievements: [
          "Responsible for the front-end development of a web application for RV and caravan rentals.",
          "Collaborated with designers and developers to implement new features and optimize UI for performance and speed.",
          "Implemented Redux Query for state management and ensured high scalability of the application.",
        ],
        technologies: [
          "Next JS",
          "Tailwind CSS",
          "Redux Query",
          "GraphQL",
          "AWS",
          "Sendbird Chat SDK",
          "Shufti Pro KYC Verification",
        ],
      },
      {
        title: "Frontend Developer - Admin Panel for E-Scooter Rental Service",
        company: "Freelance/Contract",
        projectTitle: "2022 - 2023",
        achievements: [
          "Designed and implemented reusable components for the admin panel to improve maintainability and speed.",
          "Optimized the application for high performance, ensuring it scales well for future use.",
          "Provided technical support during deployment to ensure smooth transitions to live environments.",
        ],
        technologies: ["Next JS", "Tailwind CSS", "Redux Toolkit", "AWS"],
      },
      {
        title: "Frontend Developer - Trading Analysis Web Application",
        company: "Freelance/Contract",
        projectTitle: "2021 - 2022",
        achievements: [
          "Ensured cross-device and cross-browser compatibility, making the application accessible on all devices.",
          "Managed large datasets in real-time for interactive chart updates.",
          "Integrated new features into the existing application without breaking the workflow.",
        ],
        technologies: ["Highcharts", "React JS", "JavaScript", "HTML5", "CSS3"],
      },
      {
        title: "Frontend Developer - Live & Virtual Events Hosting Platform",
        company: "Freelance/Contract",
        projectTitle: "2020 - 2021",
        achievements: [
          "Designed and implemented intuitive and user-friendly interfaces for event creation and management.",
          "Integrated various third-party APIs for payment processing, live updates, and notifications.",
          "Collaborated closely with the UX team to ensure a seamless and enjoyable user experience.",
        ],
        technologies: [
          "React JS",
          "JavaScript",
          "Tailwind CSS",
          "Redux Toolkit",
        ],
      },
      {
        title: "Frontend Developer - Online Dating and Chat Application",
        company: "Freelance/Contract",
        projectTitle: "2020 - 2021",
        achievements: [
          "Responsible for front-end development and implementation of new features in a real-time dating and chat application.",
          "Integrated real-time messaging features using WebSocket and managed state with Redux Query.",
          "Optimized the application for speed and performance using modern web technologies.",
        ],
        technologies: [
          "Next JS",
          "Tailwind CSS",
          "React Query",
          "REST APIs",
          "Web Socket",
          "AWS",
        ],
      },
    ],
    education: [
      {
        degree: "B. Tech - Information and Communication Technology (ICT)",
        description: "Focus on Web Development and Software Engineering.",
      },
    ],
  },
  {
    id: "3",
    name: "Pratik",
    title: "Front-End Developer",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "8 years",
    availability: "Available in 2 weeks",
    summary:
      "8 years of hands-on experience in front-end development, specializing in React.js, Next.js, custom state management, and UI/UX optimization. Expertise in building complex, scalable web applications with high performance and a focus on maintainability. Strong leadership skills, having led teams and provided technical insights during agile development cycles. Adept at creating seamless, cross-browser compatible experiences, and ensuring high-quality deliverables with automated testing.",
    skills: [
      {
        category: "Frontend Development",
        items: [
          "React.js",
          "Next.js",
          "JavaScript ES6",
          "TypeScript",
          "Redux",
          "Web Components",
          "React Hooks",
          "Custom State Management",
        ],
      },
      {
        category: "Testing & Debugging",
        items: [
          "Jest",
          "React Testing Library",
          "Cypress",
          "Unit Testing",
          "Code Debugging",
        ],
      },
      {
        category: "Backend Integration",
        items: [
          "Node.js",
          "Express.js",
          "RESTful APIs",
          "GraphQL",
          "MongoDB",
          "MySQL",
          "AWS Lambda",
          "PostgreSQL",
        ],
      },
      {
        category: "UI/UX Design",
        items: [
          "Material UI",
          "Ant Design",
          "Styled Components",
          "Bootstrap",
          "D3.js",
          "Charting and Data Visualization",
        ],
      },
    ],
    workExperience: [
      {
        title: "Frontend Developer - Mixed Media Art Analytics Dashboard",
        company: "Freelance/Contract",
        projectTitle: "2022 - Present",
        achievements: [
          "Developed both frontend and backend for the art analytics platform in an agile environment.",
          "Implemented JWT token-based authentication and role-based access control for secure data handling.",
          "Integrated Google Cloud Storage for secure media uploads, and managed CSV-based data propagation and validation.",
        ],
        technologies: [
          "React",
          "Next.js",
          "React Hooks",
          "Redux",
          "D3.js",
          "Express.js",
          "Node.js",
          "MongoDB",
          "TypeScript",
          "Google Cloud Storage",
        ],
      },
      {
        title: "Frontend Developer - Recruitment as a Service Platform",
        company: "Freelance/Contract",
        projectTitle: "2021 - 2022",
        achievements: [
          "Developed frontend components for a recruitment platform using GraphQL for data fetching.",
          "Worked with the design team to address UX challenges and deliver an optimal user experience.",
          "Collaborated with hiring managers to gather insights for feature development and user flow.",
        ],
        technologies: [
          "React",
          "Apollo-GraphQL",
          "React Hooks",
          "Redux",
          "Material UI",
          "Express.js",
          "Node.js",
          "TypeScript",
          "Cypress",
        ],
      },
      {
        title: "Frontend Developer - AI-based Math Learning Platform",
        company: "Freelance/Contract",
        projectTitle: "2020 - 2021",
        achievements: [
          "Developed a user-friendly interface with accessibility features (a11y) for school children.",
          "Designed and deployed a Python-based question generator on AWS Lambda for personalized learning experiences.",
          "Collaborated with tutors to enhance tutor dashboards and reporting features for students.",
        ],
        technologies: [
          "Node.js",
          "React",
          "Ant Design",
          "React Hooks",
          "Redux",
          "Express.js",
          "JavaScript ES6",
          "AWS Lambda (Python)",
          "Docker",
        ],
      },
      {
        title: "Frontend Developer - Cryptocurrency Tracker Dashboard",
        company: "Freelance/Contract",
        projectTitle: "2019 - 2020",
        achievements: [
          "Built a cryptocurrency dashboard with real-time data updates from the CoinMarketCap API.",
          "Implemented data visualizations using scatter plots and ApexCharts for real-time market analysis.",
          "Developed a custom real-time data handler for Bittrex API using Python for continuous data updates.",
        ],
        technologies: [
          "React",
          "Redux",
          "D3.js",
          "ApexCharts",
          "HTML5",
          "CSS3",
          "RESTful APIs",
          "MySQL",
          "Express.js",
          "Node.js",
        ],
      },
      {
        title: "Frontend Developer - Internal Train Travel Monitoring System",
        company: "Freelance/Contract",
        projectTitle: "2018 - 2019",
        achievements: [
          "Developed an internal data visualization system for railway transportation, improving staff decision-making.",
          "Ensured application responsiveness across devices and optimized data handling for scalability.",
          "Secured the deployed system with Apache Nginx reverse proxy for secure access and deployment.",
        ],
        technologies: [
          "React",
          "JavaScript ES6",
          "React Hooks",
          "D3.js",
          "Django",
          "Django Rest Framework",
          "PostgreSQL",
          "HTML5",
          "SQL",
          "AWS EC2",
          "Oracle 19c",
        ],
      },
      {
        title:
          "Frontend Developer - Executive Skill Assessment and Management Admin Platform",
        company: "Freelance/Contract",
        projectTitle: "2017 - 2018",
        achievements: [
          "Led a team, guiding development practices and ensuring high-quality code using Redux Toolkit and React Hooks.",
          "Worked on feature enhancements and collaborated with QA to streamline development cycles and improve code quality.",
          "Managed the integration of AWS Lambda for backend services and ensured smooth data synchronization.",
        ],
        technologies: [
          "React.js",
          "React Hooks",
          "Redux",
          "Redux Toolkit",
          "Material UI",
          "Luxon",
          "Django",
          "AWS Lambda",
          "MongoDB",
          "PostgreSQL",
        ],
      },
    ],
    education: [
      {
        degree: "B.Tech in Computer Science",
        description: "Focus on Web Development and Full Stack Engineering.",
      },
    ],
  },
  {
    id: "4",
    name: "Anshul",
    title: "Senior Backend Developer",
    avatar:
      "https://images.unsplash.com/photo-1495742290995-1b833c34a431?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "6+ Years",
    availability: "Available immediately",
    summary:
      "A Senior Backend Developer with 6+ years of experience specializing in server-side development using JavaScript and TypeScript. Expertise in designing and building high-performance APIs, working with databases like MongoDB and PostgreSQL, and developing microservices. Deep understanding of serverless architecture, Node.js, and asynchronous programming. Proven experience in optimizing API performance, implementing security best practices, and handling large-scale data processing.",
    skills: [
      {
        category: "Backend Development",
        items: [
          "Node.js",
          "Express.js",
          "TypeScript",
          "REST APIs",
          "GraphQL",
          "Microservices Architecture",
          "JWT Authentication",
        ],
      },
      {
        category: "Database Management",
        items: ["MongoDB", "PostgreSQL", "MySQL", "Redis"],
      },
      {
        category: "DevOps & CI/CD",
        items: [
          "Docker",
          "Kubernetes",
          "AWS (Lambda, EC2, S3)",
          "Terraform",
          "CI/CD Pipelines",
        ],
      },
      {
        category: "Testing & Debugging",
        items: ["Jest", "Mocha", "Chai", "Supertest", "New Relic"],
      },
    ],
    workExperience: [
      {
        title: "Senior Backend Developer",
        company: "CloudX Technologies",
        projectTitle: "Data Analytics Platform",
        achievements: [
          "Designed and developed scalable REST APIs using Node.js and Express.js to handle large data sets.",
          "Implemented GraphQL to support flexible and efficient querying of large-scale data.",
          "Deployed microservices architecture using Docker and Kubernetes on AWS infrastructure.",
          "Optimized database performance by implementing indexing and caching using Redis, reducing query times by 30%.",
          "Implemented unit and integration tests with Jest, ensuring 95% code coverage.",
        ],
        technologies: [
          "Node.js",
          "Express.js",
          "GraphQL",
          "AWS Lambda",
          "MongoDB",
          "PostgreSQL",
          "Docker",
          "Redis",
          "Jest",
          "CI/CD",
        ],
      },
      {
        title: "Backend Developer",
        company: "TechSavvy Solutions",
        projectTitle: "CRM System",
        achievements: [
          "Built high-performance backend services using Node.js and TypeScript for the CRM system.",
          "Optimized database performance and ensured data consistency with PostgreSQL.",
          "Integrated third-party APIs for email and messaging functionalities.",
          "Introduced automated deployment pipelines and containerization using Docker.",
        ],
        technologies: [
          "Node.js",
          "TypeScript",
          "Express.js",
          "PostgreSQL",
          "Docker",
          "Redis",
        ],
      },
    ],
    education: [
      {
        degree: "B.Tech in Information Technology",
        description: "Focus on Backend Development and Distributed Systems.",
      },
    ],
  },
  {
    id: "5",
    name: "Sr Unity Developer",
    title: "Senior Unity Developer",
    avatar: "",
    location: "Remote",
    yearsOfExperience: "4.9 Years",
    availability: "Available immediately",
    summary:
      "A Senior Unity Developer with 4.9 years of experience, having developed 45+ projects in Unity. Proficient in AR/VR applications, multiplayer game development, and Metaverse solutions. Experienced in building apps and games for Apple, Android, Quest, and WEBGL.",
    skills: [
      {
        category: "Game Development",
        items: [
          "Unity 3D",
          "Mirror SDK",
          "Photon SDK",
          "ReadyPlayerMe Avatar SDK",
          "3D Avatar SDK",
        ],
      },
      {
        category: "Cloud & Backend",
        items: ["AWS Cloud"],
      },
    ],
    workExperience: [
      {
        title: "Senior Unity Developer",
        company: "Freelance",
        projectTitle: "One Breath Metaverse",
        achievements: [
          "Developed a Metaverse platform for coaches and athletes, featuring games, social zones, and learning areas.",
          "Implemented multiplayer interactions and social engagement zones.",
          "Designed immersive history and learning zones for user education.",
        ],
        technologies: ["Unity 3D", "Mirror SDK", "Photon SDK", "AWS Cloud"],
      },
      {
        title: "Senior Unity Developer",
        company: "Freelance",
        projectTitle: "Skillset Aviation Metaverse",
        achievements: [
          "Built a specialized training Metaverse for helicopter pilots.",
          "Developed interactive 3D training with real-time instructor sessions.",
          "Implemented a virtual library, podcast zone, and an auditorium for training.",
        ],
        technologies: ["Unity 3D", "Mirror SDK", "Photon SDK", "AWS Cloud"],
      },
      {
        title: "Unity Developer",
        company: "Freelance",
        projectTitle: "AR Applications",
        achievements: [
          "Developed Walkopoly, a location-based AR app for rewards and ads.",
          "Created Quippo, an AR app for interactive brand engagement.",
          "Built a University Library app, a virtual guide for locating books.",
        ],
        technologies: ["Unity 3D", "AR SDKs"],
      },
      {
        title: "Unity Developer",
        company: "Freelance",
        projectTitle: "Game Development",
        achievements: [
          "Developed a VR Multiplayer Shooting Game.",
          "Created a multiplayer Baseball Game.",
          "Designed and developed a browser-based Retro Themed Car Game.",
          "Built Hero Dash, an endless runner game similar to Subway Surfer.",
          "Developed a MOBA fantasy fighting game with 5 vs. 5 gameplay.",
        ],
        technologies: ["Unity 3D", "Multiplayer SDKs"],
      },
    ],
    education: [
      {
        degree: "B.Tech in Computer Science",
        description: "Focus on Game Development and AR/VR Technologies.",
      },
    ],
  },
  {
    id: "6",
    name: "Vijay",
    title: "Technical Lead",
    avatar: "",
    location: "Remote",
    yearsOfExperience: "12.6+ Years",
    availability: "Available immediately",
    summary:
      "A seasoned Technical Lead with over 12.6 years of experience in the software industry, driving innovation through full-stack development, team leadership, and strategic vision. Renowned for architecting scalable, high-performance applications using cutting-edge technologies like ReactJS, NextJS, React Native, Flutter, Redux, NodeJS, and TypeScript. Excels in leading cross-functional teams, fostering collaboration, and delivering transformative solutions across diverse domains including banking, healthcare, hospitality, retail, and delivery services. Passionate about mentoring developers, optimizing development workflows, and spearheading advanced architectures such as Micro Frontends, serverless systems, and event-driven designs to achieve business objectives. Recognized for aligning technical strategies with organizational goals, reducing time-to-market, and enhancing user experiences through a blend of technical expertise and leadership acumen.",
    skills: [
      {
        category: "Libraries & Frameworks",
        items: [
          "ReactJS",
          "NextJS",
          "NodeJS",
          "Redux",
          "ReduxToolkit",
          "ReduxSaga",
          "ReactNative",
          "Flutter",
          "GraphQL",
          "ExpressJS",
          "NestJS",
          "Vue.js",
          "Angular",
        ],
      },
      {
        category: "Languages",
        items: [
          "Dart",
          "JavaScript",
          "TypeScript",
          "Swift",
          "Java",
          "Python",
          "HTML5",
          "CSS3",
          "Tailwind CSS",
          "StyledComponents",
          "Kotlin",
        ],
      },
      {
        category: "UI Libraries",
        items: ["MUI", "AntD", "ReactNativeBase", "Chakra UI", "Bootstrap"],
      },
      {
        category: "Project Management Tools",
        items: [
          "JIRA",
          "Slack",
          "Azure DevOps",
          "AWS",
          "Trello",
          "Confluence",
          "Asana",
          "Monday.com",
        ],
      },
      {
        category: "CI/CD Pipeline",
        items: [
          "Jenkins",
          "CircleCI",
          "GitHub Actions",
          "Docker",
          "Kubernetes",
          "Terraform",
          "ArgoCD",
        ],
      },
      {
        category: "Version Controls",
        items: [
          "GitHub",
          "GitLab",
          "Bitbucket",
          "Webpack",
          "Babel",
          "Vite",
          "SVN",
        ],
      },
      {
        category: "Micro Frontend & Monorepo",
        items: ["Yarn Workspace", "Webpack", "Nx", "Turborepo", "Lerna"],
      },
      {
        category: "Testing",
        items: [
          "React Testing Library",
          "Jest",
          "Cypress",
          "Mocha",
          "Enzyme",
          "Playwright",
          "Selenium",
        ],
      },
      {
        category: "AWS",
        items: [
          "EC2",
          "S3",
          "Lambda",
          "RDS",
          "CloudFormation",
          "API Gateway",
          "DynamoDB",
          "Elastic Beanstalk",
          "CloudWatch",
        ],
      },
      {
        category: "Databases",
        items: [
          "MySQL",
          "PostgreSQL",
          "MongoDB",
          "Firebase",
          "Redis",
          "SQLite",
          "Oracle",
        ],
      },
      {
        category: "Architecture & Design Patterns",
        items: [
          "Microservices",
          "Serverless",
          "Event-Driven Architecture",
          "MVVM",
          "MVC",
          "RESTful APIs",
          "CQRS",
        ],
      },
    ],
    workExperience: [
      {
        title: "Technical Lead",
        company: "Zyelon",
        projectTitle: "BBL - Web Application",
        achievements: [
          "Led the development of a web application to manage user accounts for BBL Bank, handling savings accounts, credit cards, and transaction workflows for over 50,000 users.",
          "Implemented Micro Frontend and MVVM architecture to enhance scalability and maintainability, reducing deployment times by 30% and enabling independent team scaling.",
          "Mentored a team of 8 developers, fostering a culture of continuous learning and ensuring adherence to coding standards and agile practices.",
          "Collaborated with product managers to align technical deliverables with business KPIs, improving customer retention by 15%.",
        ],
        technologies: [
          "NextJS",
          "TypeScript",
          "Redux",
          "ReduxSaga",
          "Redux-Toolkit",
          "GraphQL",
        ],
      },
      {
        title: "Technical Lead",
        company: "Zyelon",
        projectTitle: "BBL - Atta Wallet Web Application",
        achievements: [
          "Designed and developed a wallet management web application for BBL Bank, enabling seamless digital transactions for 20,000+ users with 99.9% uptime.",
          "Managed a distributed team of 6 engineers across time zones, delivering the project 2 weeks ahead of schedule through effective sprint planning.",
          "Integrated real-time analytics dashboards using AWS Lambda and S3, improving user engagement by 25% and providing actionable insights to stakeholders.",
          "Introduced automated testing with Jest and Cypress, reducing production bugs by 20%.",
        ],
        technologies: [
          "NextJS",
          "TypeScript",
          "Redux",
          "ReduxSaga",
          "Redux-Toolkit",
          "AWS",
        ],
      },
      {
        title: "Technical Lead",
        company: "Zyelon",
        projectTitle: "AFH - City Center Web Portal",
        achievements: [
          "Architected a portal to manage shop details for City Center mall in Saudi Arabia, tracking ownership, shop metrics, and inventory for over 300 stores with real-time updates.",
          "Led a team of 5 developers, introducing CI/CD pipelines with Jenkins to streamline releases and reduce bugs by 40%, enhancing operational reliability.",
          "Optimized performance using NextJS SSR, cutting page load times by 50% and improving SEO rankings.",
          "Facilitated cross-departmental workshops to align technical solutions with business needs, driving a 10% increase in vendor satisfaction.",
        ],
        technologies: [
          "NextJS",
          "TypeScript",
          "Redux",
          "ReduxSaga",
          "Redux-Toolkit",
          "Jenkins",
        ],
      },
      {
        title: "Technical Lead",
        company: "Zyelon",
        projectTitle: "Innergy",
        achievements: [
          "Spearheaded a health-focused mobile and web application to enhance user well-being, achieving a 4.8/5 user rating on app stores within 3 months of launch.",
          "Led a team of 7 in building content-rich features, integrating gamification to boost user retention by 35% and daily active users by 20%.",
          "Introduced Flutter for cross-platform development, reducing development time by 20% and maintenance costs by 15%.",
          "Presented app performance metrics to C-level executives, securing additional funding for feature expansion.",
        ],
        technologies: [
          "NextJS",
          "React Native",
          "Flutter",
          "JavaScript",
          "Redux",
          "ReduxSaga",
          "Redux-Toolkit",
        ],
      },
      {
        title: "Technical Lead",
        company: "Previous Company",
        projectTitle: "Inspire Brands",
        achievements: [
          "Developed a multi-brand restaurant platform managing operations for 5 brands and 200+ locations, processing 100,000+ monthly transactions.",
          "Led a team of 10 developers, implementing a modular architecture that reduced feature deployment time by 25% and improved system resilience.",
          "Integrated third-party APIs for payment (Stripe, PayPal) and logistics (Uber Eats), improving operational efficiency by 30% and customer satisfaction by 18%.",
          "Authored technical documentation and conducted knowledge-sharing sessions, upskilling junior developers.",
        ],
        technologies: [
          "NextJS",
          "ReactJS",
          "React Native",
          "TypeScript",
          "Redux",
          "ReduxSaga",
          "NodeJS",
        ],
      },
      {
        title: "Technical Lead",
        company: "Previous Company",
        projectTitle: "MCW - Mister Car Wash",
        achievements: [
          "Built a full-stack application for car wash bookings and plan management, serving 15,000+ users monthly with a 95% satisfaction rate.",
          "Led front-end and back-end teams of 6, introducing TypeScript to enhance code quality and reduce errors by 35%, setting a precedent for future projects.",
          "Optimized NodeJS APIs with caching (Redis), improving response times by 40% and handling peak loads of 1,000 requests/minute.",
          "Pioneered a reusable component library, accelerating development cycles by 15%.",
        ],
        technologies: [
          "NextJS",
          "React Native",
          "ReactJS",
          "TypeScript",
          "MySQL",
          "NodeJS",
        ],
      },
      {
        title: "Technical Lead",
        company: "Previous Company",
        projectTitle: "Deleezy - Delivery Services",
        achievements: [
          "Directed development of a mobile delivery tracking solution, managing logistics for 10,000+ orders monthly across 5 cities.",
          "Led a team of 4, implementing real-time tracking with React Native and WebSocket, boosting customer satisfaction by 20%.",
          "Streamlined deployment with CircleCI, cutting release cycles by 15% and enabling bi-weekly updates.",
          "Negotiated with third-party logistics providers to integrate APIs, reducing delivery delays by 10%.",
        ],
        technologies: ["ReactJS", "React Native", "JavaScript", "CircleCI"],
      },
      {
        title: "Senior Developer",
        company: "Previous Company",
        projectTitle: "Fab Hotel",
        achievements: [
          "Developed a mobile booking platform for flights and hotels, achieving 50,000+ downloads within 6 months and a 4.6/5 rating.",
          "Introduced Redux Saga for state management, improving app performance by 30% and simplifying debugging.",
          "Collaborated with UX designers to enhance user flows, increasing bookings by 25% and reducing cart abandonment by 12%.",
          "Transitioned legacy code to TypeScript, enhancing maintainability.",
        ],
        technologies: [
          "ReactJS",
          "React Native",
          "Redux",
          "ReduxSaga",
          "ReduxToolkit",
          "TypeScript",
        ],
      },
      {
        title: "Developer",
        company: "Previous Company",
        projectTitle: "Skill Up",
        achievements: [
          "Built a web platform managing 5,000+ students, courses, and instructors with a 98% uptime.",
          "Optimized front-end performance with ReactJS, reducing load times by 20% and improving user experience.",
          "Contributed to RESTful API design for seamless data integration, supporting 500 concurrent users.",
          "Received recognition for proactive bug resolution, reducing support tickets by 15%.",
        ],
        technologies: ["ReactJS", "Redux", "ReduxSaga", "TypeScript"],
      },
      {
        title: "Developer",
        company: "Previous Company",
        projectTitle: "Telecom - Gifting/Voucher Management",
        achievements: [
          "Developed a mobile solution for gifting data cards and vouchers, processing 10,000+ transactions monthly with zero downtime.",
          "Enhanced UI/UX with TypeScript and React Native, improving user satisfaction by 15% based on feedback surveys.",
          "Collaborated with backend teams to ensure secure payment integrations using OAuth, enhancing transaction security.",
          "Streamlined codebase, reducing technical debt by 10%.",
        ],
        technologies: [
          "ReactJS",
          "React Native",
          "Redux",
          "ReduxSaga",
          "TypeScript",
        ],
      },
      {
        title: "Developer",
        company: "Previous Company",
        projectTitle: "InMemoryOfYou",
        achievements: [
          "Created a mobile app for managing data and sending vouchers, achieving a 4.5/5 rating within 2 months of launch.",
          "Implemented Redux for state management, enhancing app stability and reducing crash rates by 10%.",
          "Contributed to rapid prototyping and deployment, delivering the MVP in 6 weeks.",
          "Supported QA efforts, ensuring 95% test coverage.",
        ],
        technologies: [
          "ReactNative",
          "ReactJS",
          "Redux",
          "ReduxSaga",
          "TypeScript",
        ],
      },
      {
        title: "Developer",
        company: "Previous Company",
        projectTitle: "MySportsClub",
        achievements: [
          "Developed an Android app for Town Sports International, managing memberships and reservations for 1,000+ users.",
          "Integrated exercise tracking and instructor scheduling features, increasing user engagement by 20%.",
          "Improved app performance with optimized Java code, reducing memory usage by 15%.",
          "Assisted in user acceptance testing, ensuring a smooth rollout.",
        ],
        technologies: ["Android Platform", "Java"],
      },
      {
        title: "Developer",
        company: "Previous Company",
        projectTitle: "Bio Tracker",
        achievements: [
          "Built an Android app for farmers to manage farm data and crops on Google Maps, serving 500+ users across rural areas.",
          "Integrated social media logins and weather APIs for enhanced functionality, improving usability by 25%.",
          "Reduced app crashes by 20% through rigorous testing and debugging.",
          "Documented API integrations for future reference.",
        ],
        technologies: ["Android Platform", "Java"],
      },
      {
        title: "Developer",
        company: "Previous Company",
        projectTitle: "Diabetes Tracker",
        achievements: [
          "Developed an Android app to track diabetes metrics and doctor visits for 300+ users, improving health management adherence by 30%.",
          "Designed a user-friendly interface for health data management, earning positive feedback from 90% of users.",
          "Contributed to feature planning and execution, delivering core features on schedule.",
          "Optimized SQLite queries, enhancing data retrieval speed by 15%.",
        ],
        technologies: ["Android Platform", "Java"],
      },
      {
        title: "Developer",
        company: "Previous Company",
        projectTitle: "Party Finder",
        achievements: [
          "Created an Android app for event browsing and ticket booking, handling 1,000+ events and 5,000+ monthly users.",
          "Implemented recommendation algorithms to improve user engagement, increasing ticket sales by 18%.",
          "Collaborated with designers for a seamless UI, reducing navigation time by 10%.",
          "Performed unit testing to ensure feature reliability.",
        ],
        technologies: ["Android Platform", "Java"],
      },
      {
        title: "Developer",
        company: "Previous Company",
        projectTitle: "GRB Shop",
        achievements: [
          "Developed a bulk-ordering platform for multi-brand products, processing 500+ orders monthly with a 98% success rate.",
          "Optimized MySQL database queries for faster order retrieval, reducing processing time by 20%.",
          "Contributed to end-to-end development lifecycle, from requirements gathering to deployment.",
          "Enhanced security with input validation, mitigating SQL injection risks.",
        ],
        technologies: ["Core PHP", "HTML", "MySQL", "CSS"],
      },
      {
        title: "Developer",
        company: "Previous Company",
        projectTitle: "Essence Web",
        achievements: [
          "Built an informative website for an IT firm, improving online presence and driving a 40% increase in client inquiries.",
          "Designed responsive layouts with HTML and CSS, ensuring mobile compatibility.",
          "Ensured cross-browser compatibility, achieving 95% consistency across major browsers.",
          "Collaborated with stakeholders to refine content strategy.",
        ],
        technologies: ["Core PHP", "HTML", "MySQL", "CSS"],
      },
    ],
    education: [
      {
        degree: "Diploma in Software Engineering (GNIIT)",
        description:
          "Completed at NIIT in 2013 with a focus on software development methodologies, programming fundamentals, and emerging technologies, earning distinction for a capstone project on e-commerce systems.",
      },
      {
        degree: "B.Sc.",
        description:
          "Completed at Dronacharya Govt. College, Gurgaon, Haryana in 2007, building a strong foundation in analytical thinking, problem-solving, and mathematical modeling.",
      },
    ],
  },
  {
    id: "7",
    name: "Anand Tupe",
    title: "Technical Lead | Full Stack Architect",
    avatar: "",
    location: "Remote",
    yearsOfExperience: "10+ Years",
    availability: "Available immediately",
    summary:
      "As a seasoned Technical Lead and Full Stack Architect with	over 10	years	of experience, I bring over a decade of expertise in designing, developing, and optimizing cutting-edge web applications. I specialize in building scalable, high-performance applications using React.js, Angular, Node.js, JavaScript, and cloud technologies. With a strong foundation in system architecture, UI/UX design, and backend optimization, I have successfully led teams in delivering robust and innovative solutions. I am passionate about mentoring developers, driving best practices, and ensuring seamless integration between frontend and backend systems. My ability to strategize, architect, and execute complex projects has consistently resulted in high-impact solutions for businesses. I am eager to bring my leadership and technical expertise to pioneering projects that push the boundaries of web development.",
    skills: [
      {
        category: "Languages",
        items: ["TypeScript", "JavaScript", "HTML", "CSS"],
      },
      {
        category: "Libraries & Frameworks",
        items: [
          "AngularJS",
          "Angular Material",
          "Angular (8 to 19)",
          "React",
          "Ionic",
          "Cloud Functions",
          "Bootstrap",
          "Node.js",
          "Express",
          "TypeScript",
        ],
      },
      {
        category: "Databases",
        items: ["Firebase", "PostgreSQL", "MySQL", "MongoDB"],
      },
      {
        category: "Cloud & DevOps",
        items: ["AWS", "GCP", "CI/CD", "Docker", "Kubernetes"],
      },
      {
        category: "Web Services & API Design",
        items: ["REST API", "GraphQL", "Microservices Architecture"],
      },
      {
        category: "Stack",
        items: ["MERN", "MEAN"],
      },
      {
        category: "IDE & Tools",
        items: ["Visual Studio Code", "JIRA", "Git", "Jenkins"],
      },
      {
        category: "Integration of Third-party APIs",
        items: ["Google Segment", "One Signal", "GTM"],
      },
      {
        category: "Testing & Security",
        items: ["Cypress", "Unit Testing", "OWASP Security Practices"],
      },
    ],
    workExperience: [
      {
        title: "Technical Lead | Full Stack Architect",
        company: "Not specified",
        projectTitle: "Lotto Social",
        achievements: [
          "Architected and led the development of a high-performance player dashboard, improving user engagement by 30%.",
          "Designed and implemented scalable frontend-backend integrations, ensuring seamless data synchronization and performance optimization.",
          "Spearheaded Agile development practices, conducting sprint planning, code reviews, and mentoring junior developers.",
        ],
        technologies: ["AngularJS", "Node.js", "MongoDB", "AWS"],
      },
      {
        title: "Technical Lead | Angular Specialist",
        company: "Not specified",
        projectTitle: "BOLSTART",
        achievements: [
          "Led the design and development of a scalable MEAN stack architecture, optimizing API response times by 40%.",
          "Implemented reusable UI components and design patterns, ensuring a modular and maintainable codebase.",
          "Championed best practices in unit testing, reducing production bugs by 25%.",
        ],
        technologies: [
          "Angular",
          "Cloud Functions",
          "Node.js",
          "TypeScript",
          "MongoDB",
        ],
      },
      {
        title: "Technical Lead | Full Stack Development",
        company: "Not specified",
        projectTitle: "Dry Sign",
        achievements: [
          "Designed and implemented a digital signature platform with government-approved verification, enhancing security and compliance.",
          "Optimized system performance and security, reducing document processing time by 35%.",
          "Led a cross-functional team, aligning business objectives with technical execution.",
        ],
        technologies: ["Angular", "Node.js", "TypeScript"],
      },
      {
        title: "Technical Lead | Software Architect",
        company: "Not specified",
        projectTitle: "Verdethos",
        achievements: [
          "Architected a supply chain management platform, improving operational efficiency by 50%.",
          "Ensured compliance with accessibility standards and optimized UI for better user engagement.",
        ],
        technologies: ["Angular", "MySQL", "TypeScript", "Node.js", "MongoDB"],
      },
      {
        title: "Senior Full Stack Developer | Technical Lead",
        company: "Not specified",
        projectTitle: "Finitee",
        achievements: [
          "Developed and launched cross-platform mobile applications using Ionic and Angular, reducing development time by 40%.",
          "Designed scalable real-time data rendering solutions for job portal and chat features.",
        ],
        technologies: [
          "Angular",
          "AngularJS",
          "Node.js",
          "Firebase",
          "Cloud Functions",
        ],
      },
      {
        title: "Senior Backend Developer | Team Lead",
        company: "Not specified",
        projectTitle: "IRIS GST - LMS, EWB",
        achievements: [
          "Led backend development for a corporate tax filing and transportation tracking system.",
          "Defined API contracts and managed end-to-end integration with frontend systems.",
        ],
        technologies: [
          "Angular 9+",
          "Ionic",
          "HTML5",
          "CSS3",
          "Node.js",
          "JavaScript",
        ],
      },
    ],
    education: [
      {
        degree: "Bachelor's in Computer Science",
        description:
          "Completed at the University of Pune, specializing in software engineering and web development.",
      },
    ],
  },
  {
    id: "8",
    name: "Parag",
    title: "Blockchain Architect | Consultant | Developer",
    avatar: "",
    location: "Remote",
    yearsOfExperience: "7+ Years",
    availability: "Available Immediately",
    summary:
      "With over 7 years of experience as a Blockchain Architect, Consultant, and Developer, I specialize in designing and implementing innovative blockchain solutions. My expertise spans public and private blockchain platforms such as Ethereum, Hyperledger, and Quorum, along with smart contract development, NFT standards, and decentralized applications. I have a proven track record of collaborating with stakeholders to analyze requirements, architect scalable solutions, and integrate blockchain technology with existing systems. Passionate about leveraging emerging technologies, I aim to deliver secure, transparent, and efficient solutions while staying updated with industry trends and mentoring teams.",
    skills: [
      {
        category: "Blockchain Technologies",
        items: [
          "Blockchain",
          "Ethereum",
          "Bitcoin",
          "Ethereum Quorum",
          "Hyperledger Besu",
          "Hyperledger R3Corda",
          "Smart Contracts",
          "NFT Standards (ERC-721, ERC-1155, ERC-2981)",
          "Public and Private Blockchain",
        ],
      },
      {
        category: "Programming Languages & Frameworks",
        items: ["Solidity", "Web3JS", "Truffle", "Hardhat", "Remix"],
      },
      {
        category: "Tools & Protocols",
        items: ["MetaMask", "IPFS Protocol", "Geth", "Uniswap Platform"],
      },
      {
        category: "Advanced Technologies",
        items: [
          "Chat GPT3.5",
          "Lang Chain Model",
          "Open AI",
          "LLM Model",
          "Layer2 Solutions",
          "Side Chain (Polygon)",
        ],
      },
      {
        category: "Other Skills",
        items: [
          "Technical Content Writing",
          "Manual Testing",
          "User Manual Creation",
          "Business Analysis",
          "Pre-sales",
        ],
      },
    ],
    workExperience: [
      {
        title: "Blockchain Consultant and Developer",
        company: "MaxelPay",
        projectTitle: "Crypto Payment Gateway",
        achievements: [
          "Integrated various components to provide a comprehensive blockchain-based payment solution.",
          "Enabled secure, transparent, and decentralized transactions via multiple blockchain backends.",
          "Facilitated integration for e-commerce platforms and fintech apps using APIs and SDKs.",
        ],
        technologies: ["Remix", "Hardhat", "Solidity", "MetaMask"],
      },
      {
        title: "Blockchain Architect and Developer",
        company: "Zyelon",
        projectTitle: "Token House",
        achievements: [
          "Developed a pioneering platform to convert real estate into NFTs.",
          "Enhanced transaction speed and transparency for property owners using blockchain technology.",
        ],
        technologies: ["Remix", "Hardhat", "Solidity", "MetaMask"],
      },
      {
        title: "Blockchain Developer and Architect",
        company: "Zyelon",
        projectTitle: "NFT Creation on Polygon and Ethereum",
        achievements: [
          "Set up development environments and deployed smart contracts for NFT minting.",
          "Created unique digital assets representing art, video clips, and music.",
        ],
        technologies: ["Solidity", "Web3JS", "IPFS", "Hardhat", "ERC-721"],
      },
      {
        title: "Blockchain Developer",
        company: "Not specified",
        projectTitle: "Escrow Account",
        achievements: [
          "Developed a secure escrow system to regulate transactions between parties.",
          "Ensured fair and secure fund releases based on agreed conditions.",
        ],
        technologies: ["Remix", "Geth", "MetaMask"],
      },
      {
        title: "Blockchain Engineer",
        company: "CSG Karnataka e-Governance",
        projectTitle: "Private Governance Blockchain on Quorum",
        achievements: [
          "Built an online verifiable record system for vendors in the bid process.",
          "Implemented a private blockchain solution using Ethereum Quorum.",
        ],
        technologies: ["Ethereum", "Quorum"],
      },
      {
        title: "Blockchain Engineer",
        company: "Not specified",
        projectTitle: "NFT Marketplace",
        achievements: [
          "Developed a platform for buying, selling, and trading NFTs.",
          "Integrated features like wallet support, bidding, and royalty management.",
        ],
        technologies: ["Ethereum"],
      },
    ],
    education: [
      {
        degree: "B.E. (Electrical and Electronics)",
        description: "Completed in 2016.",
      },
      {
        degree: "P.G. Diploma in Computer Application",
        description: "Completed in 2018.",
      },
    ],
  },
];
