import { type Candidate } from "@/types/candidate";

export const candidates: Candidate[] = [
  {
    id: "1",
    name: "Sagar",
    title: "Lead Senior Frontend Developer",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "6+ Years",
    availability: "Immediately",
    summary:
      "Experienced Lead Senior Frontend Developer with over 6 years of expertise in creating high-performance, scalable, and user-centric web applications. Specialized in React, TypeScript, and modern frontend technologies with a deep understanding of web performance, clean code practices, and UI/UX principles. Strong background in leading teams, architecting solutions, and optimizing complex applications for both speed and maintainability.",
    skills: [
      {
        category: "Frontend Development",
        items: [
          "React",
          "Next.js",
          "TypeScript",
          "Redux / Redux Toolkit",
          "Tailwind CSS",
          "GraphQL",
          "Material UI",
          "Styled Components",
          "Web Accessibility",
          "Responsive Design",
          "Atomic Design Principles",
        ],
      },
      {
        category: "Performance Optimization",
        items: [
          "Code Splitting",
          "Lazy Loading",
          "Tree Shaking",
          "Service Workers",
          "Performance Auditing (Lighthouse)",
          "SEO Optimization",
          "Critical Rendering Path Optimization",
        ],
      },
      {
        category: "Leadership & Collaboration",
        items: [
          "Team Leadership",
          "Agile & Scrum Methodologies",
          "Code Reviews & Mentorship",
          "Stakeholder Management",
          "Cross-functional Collaboration",
          "System Design & Architecture",
        ],
      },
      {
        category: "DevOps & CI/CD (Familiar)",
        items: [
          "Git",
          "Docker",
          "AWS (EC2, S3, Lambda)",
          "CI/CD Pipelines",
          "Terraform",
          "Jenkins",
        ],
      },
    ],
    workExperience: [
      {
        title: "Lead Senior Frontend Developer",
        company: "TechCorp Inc.",
        projectTitle: "LMS Portal",
        achievements: [
          "Led the front-end development of a large-scale Learning Management System (LMS), improving user engagement and accessibility.",
          "Architected and implemented reusable component libraries with a focus on scalability and maintainability.",
          "Optimized front-end performance by utilizing lazy loading, code splitting, and efficient state management (Redux).",
          "Guided a team of frontend developers, conducted code reviews, and mentored junior developers to elevate the overall team’s performance.",
          "Worked closely with UX/UI designers to implement responsive, high-quality user interfaces, maintaining consistency across platforms.",
        ],
        technologies: [
          "React",
          "Redux",
          "Next.js",
          "TypeScript",
          "Tailwind CSS",
          "Material UI",
          "SASS",
          "GraphQL",
          "REST APIs",
          "Web Accessibility",
        ],
      },
      {
        title: "Senior Frontend Developer",
        company: "TechCorp Inc.",
        projectTitle: "Telecom Marketplace",
        achievements: [
          "Led the frontend development of an e-commerce platform, enabling a seamless user experience for B2B telecom services.",
          "Optimized complex web pages for performance, reducing load times by over 40%.",
          "Collaborated with backend engineers to design and implement REST APIs, improving data exchange efficiency.",
          "Mentored junior developers and conducted knowledge-sharing sessions on modern web development practices.",
        ],
        technologies: [
          "React",
          "Next.js",
          "Redux",
          "Tailwind CSS",
          "GraphQL",
          "HTML5",
          "CSS3",
          "JavaScript",
          "AWS",
          "REST APIs",
        ],
      },
      {
        title: "Frontend Engineer",
        company: "TechCorp Inc.",
        projectTitle: "Talent Engagement",
        achievements: [
          "Built and optimized the frontend of a talent engagement platform, significantly improving the user experience and streamlining workflows.",
          "Integrated complex UI components and managed state across large-scale applications using React and Redux.",
          "Ensured application responsiveness across multiple devices, adhering to modern frontend best practices and mobile-first design.",
          "Created reusable UI components, reducing development time for future features.",
        ],
        technologies: [
          "React",
          "Redux",
          "Next.js",
          "HTML5",
          "CSS3",
          "JavaScript",
          "SASS",
          "Bootstrap",
          "Node.js",
        ],
      },
      {
        title: "Senior UI Developer",
        company: "TechCorp Inc.",
        projectTitle: "Online Dating & Chat Application",
        achievements: [
          "Led front-end development and implemented React-based UI for a real-time messaging and dating application with over 100,000 active users.",
          "Optimized the user interface for speed and responsiveness, achieving an average performance score of 90+ on Google Lighthouse.",
          "Worked on implementing WebSocket and state management using React Query, ensuring smooth and real-time communication for users.",
        ],
        technologies: [
          "React",
          "Next.js",
          "Redux",
          "React Query",
          "Tailwind CSS",
          "Web Socket",
          "AWS",
          "GraphQL",
        ],
      },
      {
        title: "Frontend Architect",
        company: "xyz",
        projectTitle: "ChatConcept",
        achievements: [
          "Designed and architected the frontend of a comprehensive chat application, leading both the technical direction and the frontend team.",
          "Implemented advanced features such as real-time messaging, file uploads with AWS S3, and seamless socket integration using Socket.IO.",
          "Conducted architectural reviews and made key decisions on frontend structure, ensuring long-term maintainability and scalability.",
        ],
        technologies: [
          "React",
          "Redux",
          "TypeScript",
          "Next.js",
          "Socket.IO",
          "MongoDB",
          "AWS S3",
          "REST API",
          "Express",
        ],
      },
      {
        title: "Senior Frontend Developer",
        company: "xyz",
        projectTitle: "AV Compliance",
        achievements: [
          "Developed the frontend of a compliance tracking application for regulatory requirements with custom reporting features.",
          "Integrated OCR system to parse and extract text from uploaded documents, providing automated data input for users.",
          "Ensured application compliance with WCAG standards to cater to users with disabilities.",
        ],
        technologies: [
          "React",
          "Next.js",
          "TypeScript",
          "GraphQL",
          "D3.js",
          "CSS3",
          "AntD",
          "Redis",
          "REST APIs",
        ],
      },
      {
        title: "Lead Frontend Developer",
        company: "xyz",
        projectTitle: "AV Biz App",
        achievements: [
          "Led the development of a cross-platform mobile application for booking AV services, streamlining user booking experiences.",
          "Integrated Firebase for real-time database syncing and Cloud Functions for seamless backend communication.",
          "Collaborated with UX/UI designers to ensure a polished and accessible mobile interface.",
        ],
        technologies: [
          "React Native",
          "Firebase",
          "JavaScript",
          "Expo",
          "MomentJS",
          "AntD",
        ],
      },
      {
        title: "Senior Frontend Developer",
        company: "xyz",
        projectTitle: "LMS Desktop App",
        achievements: [
          "Developed a desktop application using ElectronJS to manage learning resources and administrative workflows.",
          "Integrated real-time data handling using Redux and managed complex interactions between frontend and backend systems.",
        ],
        technologies: [
          "Next.js",
          "Redux",
          "ElectronJS",
          "HTML5",
          "JavaScript",
          "SCSS",
        ],
      },
    ],
    education: [
      {
        degree: "M.S. Computer Science",
        description:
          "Focus on Distributed Systems, Machine Learning, and Cloud Computing",
      },
    ],
  },
  {
    id: "2",
    name: "Apurva",
    title: "Front-End Developer",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "4+ Years",
    availability: "immediately",
    summary:
      "4+ years of hands-on experience in front-end development, proficient in using JavaScript, React JS, and Next JS. Extensive experience in creating user-facing features, building reusable components, and optimizing applications for speed and scalability. Proven ability to work independently, take initiative, and collaborate effectively within diverse team environments. Recognized for a meticulous and detail-oriented approach, excelling in delivering high-quality code and improving development efficiency.",
    skills: [
      {
        category: "Frontend Development",
        items: [
          "JavaScript",
          "TypeScript",
          "React JS",
          "Next JS",
          "Tailwind CSS",
          "Redux",
          "GraphQL",
        ],
      },
      {
        category: "Performance Optimization",
        items: [
          "Code Splitting",
          "Lazy Loading",
          "Tree Shaking",
          "Performance Auditing (Lighthouse)",
        ],
      },
      {
        category: "API Integration",
        items: ["REST APIs", "GraphQL", "Web Socket"],
      },
      {
        category: "UI/UX Design",
        items: [
          "Responsive Design",
          "User Interface Design",
          "Cross-browser Compatibility",
        ],
      },
    ],
    workExperience: [
      {
        title:
          "Frontend Developer - Web Application for RV and Caravan Rentals",
        company: "Freelance/Contract",
        projectTitle: "2023 - Present",
        achievements: [
          "Responsible for the front-end development of a web application for RV and caravan rentals.",
          "Collaborated with designers and developers to implement new features and optimize UI for performance and speed.",
          "Implemented Redux Query for state management and ensured high scalability of the application.",
        ],
        technologies: [
          "Next JS",
          "Tailwind CSS",
          "Redux Query",
          "GraphQL",
          "AWS",
          "Sendbird Chat SDK",
          "Shufti Pro KYC Verification",
        ],
      },
      {
        title: "Frontend Developer - Admin Panel for E-Scooter Rental Service",
        company: "Freelance/Contract",
        projectTitle: "2022 - 2023",
        achievements: [
          "Designed and implemented reusable components for the admin panel to improve maintainability and speed.",
          "Optimized the application for high performance, ensuring it scales well for future use.",
          "Provided technical support during deployment to ensure smooth transitions to live environments.",
        ],
        technologies: ["Next JS", "Tailwind CSS", "Redux Toolkit", "AWS"],
      },
      {
        title: "Frontend Developer - Trading Analysis Web Application",
        company: "Freelance/Contract",
        projectTitle: "2021 - 2022",
        achievements: [
          "Ensured cross-device and cross-browser compatibility, making the application accessible on all devices.",
          "Managed large datasets in real-time for interactive chart updates.",
          "Integrated new features into the existing application without breaking the workflow.",
        ],
        technologies: ["Highcharts", "React JS", "JavaScript", "HTML5", "CSS3"],
      },
      {
        title: "Frontend Developer - Live & Virtual Events Hosting Platform",
        company: "Freelance/Contract",
        projectTitle: "2020 - 2021",
        achievements: [
          "Designed and implemented intuitive and user-friendly interfaces for event creation and management.",
          "Integrated various third-party APIs for payment processing, live updates, and notifications.",
          "Collaborated closely with the UX team to ensure a seamless and enjoyable user experience.",
        ],
        technologies: [
          "React JS",
          "JavaScript",
          "Tailwind CSS",
          "Redux Toolkit",
        ],
      },
      {
        title: "Frontend Developer - Online Dating and Chat Application",
        company: "Freelance/Contract",
        projectTitle: "2020 - 2021",
        achievements: [
          "Responsible for front-end development and implementation of new features in a real-time dating and chat application.",
          "Integrated real-time messaging features using WebSocket and managed state with Redux Query.",
          "Optimized the application for speed and performance using modern web technologies.",
        ],
        technologies: [
          "Next JS",
          "Tailwind CSS",
          "React Query",
          "REST APIs",
          "Web Socket",
          "AWS",
        ],
      },
    ],
    education: [
      {
        degree: "B. Tech - Information and Communication Technology (ICT)",
        description: "Focus on Web Development and Software Engineering.",
      },
    ],
  },
  {
    id: "3",
    name: "Pratik",
    title: "Front-End Developer",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "8 years",
    availability: "Available in 2 weeks",
    summary:
      "8 years of hands-on experience in front-end development, specializing in React.js, Next.js, custom state management, and UI/UX optimization. Expertise in building complex, scalable web applications with high performance and a focus on maintainability. Strong leadership skills, having led teams and provided technical insights during agile development cycles. Adept at creating seamless, cross-browser compatible experiences, and ensuring high-quality deliverables with automated testing.",
    skills: [
      {
        category: "Frontend Development",
        items: [
          "React.js",
          "Next.js",
          "JavaScript ES6",
          "TypeScript",
          "Redux",
          "Web Components",
          "React Hooks",
          "Custom State Management",
        ],
      },
      {
        category: "Testing & Debugging",
        items: [
          "Jest",
          "React Testing Library",
          "Cypress",
          "Unit Testing",
          "Code Debugging",
        ],
      },
      {
        category: "Backend Integration",
        items: [
          "Node.js",
          "Express.js",
          "RESTful APIs",
          "GraphQL",
          "MongoDB",
          "MySQL",
          "AWS Lambda",
          "PostgreSQL",
        ],
      },
      {
        category: "UI/UX Design",
        items: [
          "Material UI",
          "Ant Design",
          "Styled Components",
          "Bootstrap",
          "D3.js",
          "Charting and Data Visualization",
        ],
      },
    ],
    workExperience: [
      {
        title: "Frontend Developer - Mixed Media Art Analytics Dashboard",
        company: "Freelance/Contract",
        projectTitle: "2022 - Present",
        achievements: [
          "Developed both frontend and backend for the art analytics platform in an agile environment.",
          "Implemented JWT token-based authentication and role-based access control for secure data handling.",
          "Integrated Google Cloud Storage for secure media uploads, and managed CSV-based data propagation and validation.",
        ],
        technologies: [
          "React",
          "Next.js",
          "React Hooks",
          "Redux",
          "D3.js",
          "Express.js",
          "Node.js",
          "MongoDB",
          "TypeScript",
          "Google Cloud Storage",
        ],
      },
      {
        title: "Frontend Developer - Recruitment as a Service Platform",
        company: "Freelance/Contract",
        projectTitle: "2021 - 2022",
        achievements: [
          "Developed frontend components for a recruitment platform using GraphQL for data fetching.",
          "Worked with the design team to address UX challenges and deliver an optimal user experience.",
          "Collaborated with hiring managers to gather insights for feature development and user flow.",
        ],
        technologies: [
          "React",
          "Apollo-GraphQL",
          "React Hooks",
          "Redux",
          "Material UI",
          "Express.js",
          "Node.js",
          "TypeScript",
          "Cypress",
        ],
      },
      {
        title: "Frontend Developer - AI-based Math Learning Platform",
        company: "Freelance/Contract",
        projectTitle: "2020 - 2021",
        achievements: [
          "Developed a user-friendly interface with accessibility features (a11y) for school children.",
          "Designed and deployed a Python-based question generator on AWS Lambda for personalized learning experiences.",
          "Collaborated with tutors to enhance tutor dashboards and reporting features for students.",
        ],
        technologies: [
          "Node.js",
          "React",
          "Ant Design",
          "React Hooks",
          "Redux",
          "Express.js",
          "JavaScript ES6",
          "AWS Lambda (Python)",
          "Docker",
        ],
      },
      {
        title: "Frontend Developer - Cryptocurrency Tracker Dashboard",
        company: "Freelance/Contract",
        projectTitle: "2019 - 2020",
        achievements: [
          "Built a cryptocurrency dashboard with real-time data updates from the CoinMarketCap API.",
          "Implemented data visualizations using scatter plots and ApexCharts for real-time market analysis.",
          "Developed a custom real-time data handler for Bittrex API using Python for continuous data updates.",
        ],
        technologies: [
          "React",
          "Redux",
          "D3.js",
          "ApexCharts",
          "HTML5",
          "CSS3",
          "RESTful APIs",
          "MySQL",
          "Express.js",
          "Node.js",
        ],
      },
      {
        title: "Frontend Developer - Internal Train Travel Monitoring System",
        company: "Freelance/Contract",
        projectTitle: "2018 - 2019",
        achievements: [
          "Developed an internal data visualization system for railway transportation, improving staff decision-making.",
          "Ensured application responsiveness across devices and optimized data handling for scalability.",
          "Secured the deployed system with Apache Nginx reverse proxy for secure access and deployment.",
        ],
        technologies: [
          "React",
          "JavaScript ES6",
          "React Hooks",
          "D3.js",
          "Django",
          "Django Rest Framework",
          "PostgreSQL",
          "HTML5",
          "SQL",
          "AWS EC2",
          "Oracle 19c",
        ],
      },
      {
        title:
          "Frontend Developer - Executive Skill Assessment and Management Admin Platform",
        company: "Freelance/Contract",
        projectTitle: "2017 - 2018",
        achievements: [
          "Led a team, guiding development practices and ensuring high-quality code using Redux Toolkit and React Hooks.",
          "Worked on feature enhancements and collaborated with QA to streamline development cycles and improve code quality.",
          "Managed the integration of AWS Lambda for backend services and ensured smooth data synchronization.",
        ],
        technologies: [
          "React.js",
          "React Hooks",
          "Redux",
          "Redux Toolkit",
          "Material UI",
          "Luxon",
          "Django",
          "AWS Lambda",
          "MongoDB",
          "PostgreSQL",
        ],
      },
    ],
    education: [
      {
        degree: "B.Tech in Computer Science",
        description: "Focus on Web Development and Full Stack Engineering.",
      },
    ],
  },
  {
    id: "4",
    name: "Anshul",
    title: "Senior Backend Developer",
    avatar:
      "https://images.unsplash.com/photo-1495742290995-1b833c34a431?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "6+ Years",
    availability: "Available immediately",
    summary:
      "A Senior Backend Developer with 6+ years of experience specializing in server-side development using JavaScript and TypeScript. Expertise in designing and building high-performance APIs, working with databases like MongoDB and PostgreSQL, and developing microservices. Deep understanding of serverless architecture, Node.js, and asynchronous programming. Proven experience in optimizing API performance, implementing security best practices, and handling large-scale data processing.",
    skills: [
      {
        category: "Backend Development",
        items: [
          "Node.js",
          "Express.js",
          "TypeScript",
          "REST APIs",
          "GraphQL",
          "Microservices Architecture",
          "JWT Authentication",
        ],
      },
      {
        category: "Database Management",
        items: ["MongoDB", "PostgreSQL", "MySQL", "Redis"],
      },
      {
        category: "DevOps & CI/CD",
        items: [
          "Docker",
          "Kubernetes",
          "AWS (Lambda, EC2, S3)",
          "Terraform",
          "CI/CD Pipelines",
        ],
      },
      {
        category: "Testing & Debugging",
        items: ["Jest", "Mocha", "Chai", "Supertest", "New Relic"],
      },
    ],
    workExperience: [
      {
        title: "Senior Backend Developer",
        company: "CloudX Technologies",
        projectTitle: "Data Analytics Platform",
        achievements: [
          "Designed and developed scalable REST APIs using Node.js and Express.js to handle large data sets.",
          "Implemented GraphQL to support flexible and efficient querying of large-scale data.",
          "Deployed microservices architecture using Docker and Kubernetes on AWS infrastructure.",
          "Optimized database performance by implementing indexing and caching using Redis, reducing query times by 30%.",
          "Implemented unit and integration tests with Jest, ensuring 95% code coverage.",
        ],
        technologies: [
          "Node.js",
          "Express.js",
          "GraphQL",
          "AWS Lambda",
          "MongoDB",
          "PostgreSQL",
          "Docker",
          "Redis",
          "Jest",
          "CI/CD",
        ],
      },
      {
        title: "Backend Developer",
        company: "TechSavvy Solutions",
        projectTitle: "CRM System",
        achievements: [
          "Built high-performance backend services using Node.js and TypeScript for the CRM system.",
          "Optimized database performance and ensured data consistency with PostgreSQL.",
          "Integrated third-party APIs for email and messaging functionalities.",
          "Introduced automated deployment pipelines and containerization using Docker.",
        ],
        technologies: [
          "Node.js",
          "TypeScript",
          "Express.js",
          "PostgreSQL",
          "Docker",
          "Redis",
        ],
      },
    ],
    education: [
      {
        degree: "B.Tech in Information Technology",
        description: "Focus on Backend Development and Distributed Systems.",
      },
    ],
  },
  {
    id: "5",
    name: "Sr Unity Developer",
    title: "Senior Unity Developer",
    avatar: "",
    location: "Remote",
    yearsOfExperience: "4.9 Years",
    availability: "Available immediately",
    summary:
      "A Senior Unity Developer with 4.9 years of experience, having developed 45+ projects in Unity. Proficient in AR/VR applications, multiplayer game development, and Metaverse solutions. Experienced in building apps and games for Apple, Android, Quest, and WEBGL.",
    skills: [
      {
        category: "Game Development",
        items: [
          "Unity 3D",
          "Mirror SDK",
          "Photon SDK",
          "ReadyPlayerMe Avatar SDK",
          "3D Avatar SDK",
        ],
      },
      {
        category: "Cloud & Backend",
        items: ["AWS Cloud"],
      },
    ],
    workExperience: [
      {
        title: "Senior Unity Developer",
        company: "Freelance",
        projectTitle: "One Breath Metaverse",
        achievements: [
          "Developed a Metaverse platform for coaches and athletes, featuring games, social zones, and learning areas.",
          "Implemented multiplayer interactions and social engagement zones.",
          "Designed immersive history and learning zones for user education.",
        ],
        technologies: ["Unity 3D", "Mirror SDK", "Photon SDK", "AWS Cloud"],
      },
      {
        title: "Senior Unity Developer",
        company: "Freelance",
        projectTitle: "Skillset Aviation Metaverse",
        achievements: [
          "Built a specialized training Metaverse for helicopter pilots.",
          "Developed interactive 3D training with real-time instructor sessions.",
          "Implemented a virtual library, podcast zone, and an auditorium for training.",
        ],
        technologies: ["Unity 3D", "Mirror SDK", "Photon SDK", "AWS Cloud"],
      },
      {
        title: "Unity Developer",
        company: "Freelance",
        projectTitle: "AR Applications",
        achievements: [
          "Developed Walkopoly, a location-based AR app for rewards and ads.",
          "Created Quippo, an AR app for interactive brand engagement.",
          "Built a University Library app, a virtual guide for locating books.",
        ],
        technologies: ["Unity 3D", "AR SDKs"],
      },
      {
        title: "Unity Developer",
        company: "Freelance",
        projectTitle: "Game Development",
        achievements: [
          "Developed a VR Multiplayer Shooting Game.",
          "Created a multiplayer Baseball Game.",
          "Designed and developed a browser-based Retro Themed Car Game.",
          "Built Hero Dash, an endless runner game similar to Subway Surfer.",
          "Developed a MOBA fantasy fighting game with 5 vs. 5 gameplay.",
        ],
        technologies: ["Unity 3D", "Multiplayer SDKs"],
      },
    ],
    education: [
      {
        degree: "B.Tech in Computer Science",
        description: "Focus on Game Development and AR/VR Technologies.",
      },
    ],
  },
  {
    id: "6",
    name: "Vijay",
    title: "Technical Lead - Full Stack Developer",
    avatar:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "12.6+ Years",
    availability: "immediately",
    summary:
      "Over 12.6 years of experience in the software industry, specializing in full-stack development and technical leadership. Proficient in designing and developing applications using ReactJS, NextJS, React Native, Flutter, Dart, Redux, Redux-Saga, Redux-Toolkit, JavaScript, and TypeScript. Experienced in leading teams, implementing micro-frontend architectures, and managing CI/CD pipelines. Skilled in AWS services, version control systems, and modern UI frameworks, with a strong focus on delivering scalable and high-quality solutions.",
    skills: [
      {
        category: "Libraries & Frameworks",
        items: [
          "ReactJS",
          "NextJS",
          "NodeJS",
          "Redux",
          "Redux-Toolkit",
          "Redux-Saga",
          "React Native",
          "Flutter",
          "GraphQL",
          "ExpressJS",
        ],
      },
      {
        category: "Languages",
        items: [
          "Dart",
          "JavaScript",
          "TypeScript",
          "Swift",
          "Java",
          "HTML5",
          "CSS3",
          "Tailwind CSS",
          "Styled Components",
        ],
      },
      {
        category: "UI Libraries",
        items: ["Material UI (MUI)", "Ant Design (AntD)", "React Native Base"],
      },
      {
        category: "Project Management Tools",
        items: ["JIRA", "Slack", "Azure", "AWS"],
      },
      {
        category: "CI/CD Pipeline",
        items: ["Jenkins", "CircleCI"],
      },
      {
        category: "Version Control",
        items: ["GitHub", "GitLab", "Bitbucket", "Webpack", "Babel"],
      },
      {
        category: "Micro Frontend & Monorepo",
        items: ["Yarn Workspace", "Webpack"],
      },
      {
        category: "Testing",
        items: ["React Testing Library", "Jest"],
      },
      {
        category: "AWS",
        items: ["EC2", "S3", "Lambda"],
      },
    ],
    workExperience: [
      {
        title: "Technical Lead - BBL Web Application",
        company: "Zyelon",
        projectTitle: "June 2024 - Present",
        achievements: [
          "Led the development of a banking web application to manage user accounts (e.g., savings, credit cards) using NextJS and TypeScript.",
          "Implemented micro-frontend architecture and MVVM design pattern with Redux ecosystem.",
        ],
        technologies: [
          "NextJS",
          "TypeScript",
          "Redux",
          "Redux-Saga",
          "Redux-Toolkit",
        ],
      },
      {
        title: "Technical Lead - BBL Atta Wallet Web Application",
        company: "Zyelon",
        projectTitle: "Feb 2024 - May 2024",
        achievements: [
          "Led the development of a wallet management web application for BBL Bank.",
          "Utilized NextJS and Redux ecosystem for state management and scalable architecture.",
        ],
        technologies: [
          "NextJS",
          "TypeScript",
          "Redux",
          "Redux-Saga",
          "Redux-Toolkit",
        ],
      },
      {
        title: "Technical Lead - AFH City Center Web Portal",
        company: "Zyelon",
        projectTitle: "July 2023 - Jan 2024",
        achievements: [
          "Developed a web portal to manage shop records in City Center mall, Saudi Arabia.",
          "Oversaw implementation of shop ownership, inventory, and tracking features.",
        ],
        technologies: [
          "NextJS",
          "TypeScript",
          "Redux",
          "Redux-Saga",
          "Redux-Toolkit",
        ],
      },
      {
        title: "Technical Lead - Innergy",
        company: "Zyelon",
        projectTitle: "Feb 2023 - June 2023",
        achievements: [
          "Led the creation of a health-focused app to reduce stress and improve well-being.",
          "Integrated content-rich material and tips using React Native and NextJS.",
        ],
        technologies: [
          "NextJS",
          "React Native",
          "JavaScript",
          "Redux",
          "Redux-Saga",
          "Redux-Toolkit",
        ],
      },
      {
        title: "Technical Lead - Inspire Brands",
        company: "Previous Company",
        projectTitle: "Aug 2022 - In Progress (Jan 2023)",
        achievements: [
          "Developed a multi-brand restaurant management platform to unify business operations.",
          "Led the team in integrating various brands into a single scalable application.",
        ],
        technologies: [
          "NextJS",
          "ReactJS",
          "React Native",
          "TypeScript",
          "Redux",
          "Redux-Saga",
        ],
      },
      {
        title: "Technical Lead - MCW (Mister Car Wash)",
        company: "Previous Company",
        projectTitle: "Oct 2021 - Mar 2022",
        achievements: [
          "Built a car wash service app for booking slots, checking timings, and managing plans.",
          "Led integration of MySQL and NodeJS backend with React Native frontend.",
        ],
        technologies: [
          "NextJS",
          "React Native",
          "ReactJS",
          "TypeScript",
          "MySQL",
          "NodeJS",
        ],
      },
      {
        title: "Technical Lead - Deleezy Delivery Services",
        company: "Previous Company",
        projectTitle: "Mar 2021 - Oct 2021",
        achievements: [
          "Developed a mobile solution for managing and tracking delivery services.",
          "Led the implementation using ReactJS and React Native.",
        ],
        technologies: ["ReactJS", "React Native", "JavaScript"],
      },
      {
        title: "Full Stack Developer - Fab Hotel",
        company: "Previous Company",
        projectTitle: "June 2020 - Feb 2021",
        achievements: [
          "Contributed to a mobile solution for booking flights and hotels.",
          "Implemented state management with Redux and TypeScript.",
        ],
        technologies: [
          "ReactJS",
          "React Native",
          "Redux",
          "Redux-Saga",
          "Redux-Toolkit",
          "TypeScript",
        ],
      },
      {
        title: "Full Stack Developer - Skill Up",
        company: "Previous Company",
        projectTitle: "Jan 2020 - May 2021",
        achievements: [
          "Developed a web solution for managing students, courses, and instructors.",
          "Utilized ReactJS and Redux for a dynamic and responsive interface.",
        ],
        technologies: ["ReactJS", "Redux", "Redux-Saga", "TypeScript"],
      },
      {
        title: "Full Stack Developer - Telecom Gifting/Voucher Management",
        company: "Previous Company",
        projectTitle: "Dec 2018 - Dec 2019",
        achievements: [
          "Built a mobile solution for managing data cards and gifting vouchers.",
          "Contributed to end-to-end development with React Native and Redux.",
        ],
        technologies: [
          "ReactJS",
          "React Native",
          "Redux",
          "Redux-Saga",
          "TypeScript",
        ],
      },
      {
        title: "Full Stack Developer - InMemoryOfYou",
        company: "Previous Company",
        projectTitle: "Jan 2018 - Nov 2018",
        achievements: [
          "Developed a mobile app for sending data cards and vouchers as gifts.",
          "Implemented features using React Native and TypeScript.",
        ],
        technologies: [
          "React Native",
          "ReactJS",
          "Redux",
          "Redux-Saga",
          "TypeScript",
        ],
      },
      {
        title: "Android Developer - MySportsClub",
        company: "Previous Company",
        projectTitle: "June 2017 - Dec 2017",
        achievements: [
          "Built an Android app for Town Sports International to manage memberships and class schedules.",
          "Integrated features for tracking exercise and instructor details.",
        ],
        technologies: ["Android Platform", "Java"],
      },
      {
        title: "Android Developer - Bio Tracker",
        company: "Previous Company",
        projectTitle: "May 2016 - May 2017",
        achievements: [
          "Developed an app for farmers to manage farms, crops, and weather data.",
          "Integrated Google Maps and social media logins for enhanced functionality.",
        ],
        technologies: ["Android Platform", "Java"],
      },
      {
        title: "Android Developer - Diabetes Tracker",
        company: "Previous Company",
        projectTitle: "Jan 2016 - April 2016",
        achievements: [
          "Created an app to track diabetes, doctor visits, and exercise routines.",
          "Designed a user-friendly interface for health management.",
        ],
        technologies: ["Android Platform", "Java"],
      },
      {
        title: "Android Developer - Party Finder",
        company: "Previous Company",
        projectTitle: "Jan 2015 - Dec 2015",
        achievements: [
          "Developed an app to browse and book tickets for city events.",
          "Implemented recommendation and scheduling features.",
        ],
        technologies: ["Android Platform", "Java"],
      },
      {
        title: "Web Developer - GRB Shop",
        company: "Previous Company",
        projectTitle: "Jan 2014 - Dec 2014",
        achievements: [
          "Built a platform for bulk ordering of multi-brand products.",
          "Developed the solution using Core PHP and MySQL.",
        ],
        technologies: ["Core PHP", "HTML", "MySQL", "CSS"],
      },
      {
        title: "Web Developer - Essence Web",
        company: "Previous Company",
        projectTitle: "June 2013 - Dec 2013",
        achievements: [
          "Developed an informational website for an IT proprietary.",
          "Utilized Core PHP and MySQL for backend functionality.",
        ],
        technologies: ["Core PHP", "HTML", "MySQL", "CSS"],
      },
    ],
    education: [
      {
        degree: "Diploma in Software Engineering (GNIIT)",
        description: "NIIT, 2013.",
      },
      {
        degree: "B.Sc.",
        description: "Dronacharya Govt. College, Gurgaon, Haryana, 2007.",
      },
    ],
  },
  {
    id: "7",
    name: "Anand Tupe",
    title: "Technical Lead | Full Stack Architect",
    avatar: "",
    location: "Remote",
    yearsOfExperience: "10+ Years",
    availability: "Available immediately",
    summary:
      "As a seasoned Technical Lead and Full Stack Architect with	over 10	years	of experience, I bring over a decade of expertise in designing, developing, and optimizing cutting-edge web applications. I specialize in building scalable, high-performance applications using React.js, Angular, Node.js, JavaScript, and cloud technologies. With a strong foundation in system architecture, UI/UX design, and backend optimization, I have successfully led teams in delivering robust and innovative solutions. I am passionate about mentoring developers, driving best practices, and ensuring seamless integration between frontend and backend systems. My ability to strategize, architect, and execute complex projects has consistently resulted in high-impact solutions for businesses. I am eager to bring my leadership and technical expertise to pioneering projects that push the boundaries of web development.",
    skills: [
      {
        category: "Languages",
        items: ["TypeScript", "JavaScript", "HTML", "CSS"],
      },
      {
        category: "Libraries & Frameworks",
        items: [
          "AngularJS",
          "Angular Material",
          "Angular (8 to 19)",
          "React",
          "Ionic",
          "Cloud Functions",
          "Bootstrap",
          "Node.js",
          "Express",
          "TypeScript",
        ],
      },
      {
        category: "Databases",
        items: ["Firebase", "PostgreSQL", "MySQL", "MongoDB"],
      },
      {
        category: "Cloud & DevOps",
        items: ["AWS", "GCP", "CI/CD", "Docker", "Kubernetes"],
      },
      {
        category: "Web Services & API Design",
        items: ["REST API", "GraphQL", "Microservices Architecture"],
      },
      {
        category: "Stack",
        items: ["MERN", "MEAN"],
      },
      {
        category: "IDE & Tools",
        items: ["Visual Studio Code", "JIRA", "Git", "Jenkins"],
      },
      {
        category: "Integration of Third-party APIs",
        items: ["Google Segment", "One Signal", "GTM"],
      },
      {
        category: "Testing & Security",
        items: ["Cypress", "Unit Testing", "OWASP Security Practices"],
      },
    ],
    workExperience: [
      {
        title: "Technical Lead | Full Stack Architect",
        company: "Not specified",
        projectTitle: "Lotto Social",
        achievements: [
          "Architected and led the development of a high-performance player dashboard, improving user engagement by 30%.",
          "Designed and implemented scalable frontend-backend integrations, ensuring seamless data synchronization and performance optimization.",
          "Spearheaded Agile development practices, conducting sprint planning, code reviews, and mentoring junior developers.",
        ],
        technologies: ["AngularJS", "Node.js", "MongoDB", "AWS"],
      },
      {
        title: "Technical Lead | Angular Specialist",
        company: "Not specified",
        projectTitle: "BOLSTART",
        achievements: [
          "Led the design and development of a scalable MEAN stack architecture, optimizing API response times by 40%.",
          "Implemented reusable UI components and design patterns, ensuring a modular and maintainable codebase.",
          "Championed best practices in unit testing, reducing production bugs by 25%.",
        ],
        technologies: [
          "Angular",
          "Cloud Functions",
          "Node.js",
          "TypeScript",
          "MongoDB",
        ],
      },
      {
        title: "Technical Lead | Full Stack Development",
        company: "Not specified",
        projectTitle: "Dry Sign",
        achievements: [
          "Designed and implemented a digital signature platform with government-approved verification, enhancing security and compliance.",
          "Optimized system performance and security, reducing document processing time by 35%.",
          "Led a cross-functional team, aligning business objectives with technical execution.",
        ],
        technologies: ["Angular", "Node.js", "TypeScript"],
      },
      {
        title: "Technical Lead | Software Architect",
        company: "Not specified",
        projectTitle: "Verdethos",
        achievements: [
          "Architected a supply chain management platform, improving operational efficiency by 50%.",
          "Ensured compliance with accessibility standards and optimized UI for better user engagement.",
        ],
        technologies: ["Angular", "MySQL", "TypeScript", "Node.js", "MongoDB"],
      },
      {
        title: "Senior Full Stack Developer | Technical Lead",
        company: "Not specified",
        projectTitle: "Finitee",
        achievements: [
          "Developed and launched cross-platform mobile applications using Ionic and Angular, reducing development time by 40%.",
          "Designed scalable real-time data rendering solutions for job portal and chat features.",
        ],
        technologies: [
          "Angular",
          "AngularJS",
          "Node.js",
          "Firebase",
          "Cloud Functions",
        ],
      },
      {
        title: "Senior Backend Developer | Team Lead",
        company: "Not specified",
        projectTitle: "IRIS GST - LMS, EWB",
        achievements: [
          "Led backend development for a corporate tax filing and transportation tracking system.",
          "Defined API contracts and managed end-to-end integration with frontend systems.",
        ],
        technologies: [
          "Angular 9+",
          "Ionic",
          "HTML5",
          "CSS3",
          "Node.js",
          "JavaScript",
        ],
      },
    ],
    education: [
      {
        degree: "Bachelor's in Computer Science",
        description:
          "Completed at the University of Pune, specializing in software engineering and web development.",
      },
    ],
  },
  {
    id: "8",
    name: "Parag",
    title: "Blockchain Architect | Consultant | Developer",
    avatar: "",
    location: "Remote",
    yearsOfExperience: "7+ Years",
    availability: "Available Immediately",
    summary:
      "With over 7 years of experience as a Blockchain Architect, Consultant, and Developer, I specialize in designing and implementing innovative blockchain solutions. My expertise spans public and private blockchain platforms such as Ethereum, Hyperledger, and Quorum, along with smart contract development, NFT standards, and decentralized applications. I have a proven track record of collaborating with stakeholders to analyze requirements, architect scalable solutions, and integrate blockchain technology with existing systems. Passionate about leveraging emerging technologies, I aim to deliver secure, transparent, and efficient solutions while staying updated with industry trends and mentoring teams.",
    skills: [
      {
        category: "Blockchain Technologies",
        items: [
          "Blockchain",
          "Ethereum",
          "Bitcoin",
          "Ethereum Quorum",
          "Hyperledger Besu",
          "Hyperledger R3Corda",
          "Smart Contracts",
          "NFT Standards (ERC-721, ERC-1155, ERC-2981)",
          "Public and Private Blockchain",
        ],
      },
      {
        category: "Programming Languages & Frameworks",
        items: ["Solidity", "Web3JS", "Truffle", "Hardhat", "Remix"],
      },
      {
        category: "Tools & Protocols",
        items: ["MetaMask", "IPFS Protocol", "Geth", "Uniswap Platform"],
      },
      {
        category: "Advanced Technologies",
        items: [
          "Chat GPT3.5",
          "Lang Chain Model",
          "Open AI",
          "LLM Model",
          "Layer2 Solutions",
          "Side Chain (Polygon)",
        ],
      },
      {
        category: "Other Skills",
        items: [
          "Technical Content Writing",
          "Manual Testing",
          "User Manual Creation",
          "Business Analysis",
          "Pre-sales",
        ],
      },
    ],
    workExperience: [
      {
        title: "Blockchain Consultant and Developer",
        company: "MaxelPay",
        projectTitle: "Crypto Payment Gateway",
        achievements: [
          "Integrated various components to provide a comprehensive blockchain-based payment solution.",
          "Enabled secure, transparent, and decentralized transactions via multiple blockchain backends.",
          "Facilitated integration for e-commerce platforms and fintech apps using APIs and SDKs.",
        ],
        technologies: ["Remix", "Hardhat", "Solidity", "MetaMask"],
      },
      {
        title: "Blockchain Architect and Developer",
        company: "Zyelon",
        projectTitle: "Token House",
        achievements: [
          "Developed a pioneering platform to convert real estate into NFTs.",
          "Enhanced transaction speed and transparency for property owners using blockchain technology.",
        ],
        technologies: ["Remix", "Hardhat", "Solidity", "MetaMask"],
      },
      {
        title: "Blockchain Developer and Architect",
        company: "Zyelon",
        projectTitle: "NFT Creation on Polygon and Ethereum",
        achievements: [
          "Set up development environments and deployed smart contracts for NFT minting.",
          "Created unique digital assets representing art, video clips, and music.",
        ],
        technologies: ["Solidity", "Web3JS", "IPFS", "Hardhat", "ERC-721"],
      },
      {
        title: "Blockchain Developer",
        company: "Not specified",
        projectTitle: "Escrow Account",
        achievements: [
          "Developed a secure escrow system to regulate transactions between parties.",
          "Ensured fair and secure fund releases based on agreed conditions.",
        ],
        technologies: ["Remix", "Geth", "MetaMask"],
      },
      {
        title: "Blockchain Engineer",
        company: "CSG Karnataka e-Governance",
        projectTitle: "Private Governance Blockchain on Quorum",
        achievements: [
          "Built an online verifiable record system for vendors in the bid process.",
          "Implemented a private blockchain solution using Ethereum Quorum.",
        ],
        technologies: ["Ethereum", "Quorum"],
      },
      {
        title: "Blockchain Engineer",
        company: "Not specified",
        projectTitle: "NFT Marketplace",
        achievements: [
          "Developed a platform for buying, selling, and trading NFTs.",
          "Integrated features like wallet support, bidding, and royalty management.",
        ],
        technologies: ["Ethereum"],
      },
    ],
    education: [
      {
        degree: "B.E. (Electrical and Electronics)",
        description: "Completed in 2016.",
      },
      {
        degree: "P.G. Diploma in Computer Application",
        description: "Completed in 2018.",
      },
    ],
  },
  {
    id: "9",
    name: "Bhavy",
    title: "MERN Stack Developer",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "4+ Years",
    availability: "immediately",
    summary:
      "Around 4+ years of extensive experience in web-based applications using NodeJS, ExpressJS, NextJS, MongoDB, ReactJS, Redux, AngularJS, Data Visualization, and WebGL technologies. Proficient in designing and implementing various web applications in both front-end (AngularJS, ReactJS) and back-end (NodeJS, NextJS, ExpressJS, MongoDB) environments. Expertise includes server-side APIs, server-side rendering, REST API development, and architecture design for backend development with third-party integrations. Strong understanding of git versioning, API-driven design, and database optimization with MySQL and MongoDB.",
    skills: [
      {
        category: "Frontend Development",
        items: [
          "HTML5",
          "CSS3",
          "ReactJS",
          "jQuery",
          "JavaScript",
          "Bootstrap",
          "ReactBootstrap",
          "Material UI",
          "WebGL",
          "D3",
          "TypeScript",
          "AngularJS",
          "Redux",
        ],
      },
      {
        category: "Backend Development",
        items: ["NodeJS", "ExpressJS", "NextJS", "MongoDB", "MySQL"],
      },
      {
        category: "DevOps",
        items: ["Bitbucket", "Git", "GitHub Actions"],
      },
      {
        category: "Productivity",
        items: ["Jira", "Trello", "Slack", "Skype"],
      },
      {
        category: "API Integration",
        items: ["REST APIs", "Web Services", "XML"],
      },
    ],
    workExperience: [
      {
        title: "MERN Stack Developer - Webphone Dialer",
        company: "Undisclosed",
        projectTitle: "Past Project",
        achievements: [
          "Developed a web-based SIP WebRTC Dialer with chat features like one-to-one and group chat.",
          "Extensively worked on ReactJS, HTML, CSS, JavaScript, and REST APIs.",
          "Improved and corrected HTML, CSS, and JavaScript structure for better performance.",
        ],
        technologies: [
          "ReactJS",
          "NodeJS",
          "HTML",
          "CSS",
          "JavaScript",
          "REST APIs",
        ],
      },
      {
        title: "MERN Stack Developer - Notice Ninja",
        company: "Undisclosed",
        projectTitle: "Past Project",
        achievements: [
          "Developed a tax notice management and compliance application using ReactJS, NextJS, and NodeJS with MySQL database.",
          "Implemented various design patterns including MVC for efficient development.",
        ],
        technologies: ["ReactJS", "NextJS", "NodeJS", "MySQL"],
      },
      {
        title:
          "MERN Stack Developer - Upforce-EMS, Shield Kiosk, Shield Kiosk App, Shield Kiosk Admin",
        company: "Undisclosed",
        projectTitle: "Past Project",
        achievements: [
          "Developed web portals for cleaning job management and COVID-19 situation monitoring using ReactJS and NodeJS.",
          "Managed temperature tracking and live video features for working areas.",
        ],
        technologies: ["ReactJS", "NodeJS"],
      },
      {
        title:
          "MERN Stack Developer - Ekasha, Threat I, Data Visualization Library",
        company: "Undisclosed",
        projectTitle: "Past Project",
        achievements: [
          "Built a dashboard using ReactJS to maintain analytics data and visualize it in charts.",
          "Designed easy user interfaces and great user experiences for sellers.",
          "Created a data visualization library and dynamic dashboard using WebGL and D3.",
        ],
        technologies: ["ReactJS", "NextJS", "WebGL", "D3"],
      },
    ],
    education: [
      {
        degree: "BCA - Bachelor of Computer Applications",
        description: "Bhakt Kavi Narshi Mehta University, Ahmedabad.",
      },
      {
        degree: "12th State Board",
        description: "Gujarat State Board.",
      },
      {
        degree: "10th State Board",
        description: "Gujarat State Board.",
      },
    ],
  },
  {
    id: "10",
    name: "Rahul",
    title: "Full Stack Developer",
    avatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&h=300",
    location: "Remote",
    yearsOfExperience: "7+ Years",
    availability: "immediately",
    summary:
      "Over 7+ years of professional experience in IT industries with comprehensive knowledge in Software Analysis, Design, and Development of business applications. Skilled in web development technologies including Angular, ReactJS, ExtJS, Nest.js, and Node.js. Proficient in JavaScript (ES5/ES6), TypeScript, and modern frameworks with a strong focus on coding, debugging, and testing. Experienced in PostgreSQL, MongoDB, and AWS services. Adept at working in Agile environments, utilizing tools like GitHub, GitLab, and Azure for version control and project management. Known for strong communication, interpersonal skills, and the ability to adapt quickly to new technologies.",
    skills: [
      {
        category: "Frontend Development",
        items: [
          "Angular",
          "ReactJS",
          "ExtJS",
          "TypeScript",
          "JavaScript (ES5 and ES6)",
          "HTML5",
          "CSS3",
          "jQuery",
          "Bootstrap",
          "Material UI",
          "Angular Material",
          "SASS",
          "Redux",
          "AJAX",
          "JSON",
        ],
      },
      {
        category: "Backend Development",
        items: [
          "Node.js",
          "Express.js",
          "Nest.js",
          "MongoDB",
          "MySQL",
          "SQL Server",
          "PostgreSQL",
        ],
      },
      {
        category: "Cloud & DevOps",
        items: [
          "AWS (S3, SES, Cognito, Cloudwatch, Lambda, CloudFormation)",
          "Azure",
          "Git",
          "GitHub",
          "GitLab",
          "Bitbucket",
          "Sourcetree",
        ],
      },
      {
        category: "Tools",
        items: [
          "Visual Studio Code",
          "Atom",
          "Notepad++",
          "Sublime",
          "Sencha Architect",
          "Jasmine (Testing)",
        ],
      },
      {
        category: "Task and Project Management",
        items: ["Jira", "Trello", "Azure"],
      },
      {
        category: "Operating Systems",
        items: ["Windows", "Linux"],
      },
    ],
    workExperience: [
      {
        title: "Full Stack Developer - ActionPlanner",
        company: "Undisclosed",
        projectTitle: "Duration: 1 Year",
        achievements: [
          "Developed an enterprise application for store management across multiple locations with multi-tenant, multi-lingual, and multi-role capabilities.",
          "Designed and implemented the entire UI using AngularJS and Node.js.",
          "Built APIs and Lambda functions using Node.js and MongoDB, and managed deployment on Azure.",
        ],
        technologies: [
          "Node.js",
          "Express.js",
          "MongoDB",
          "JavaScript",
          "HTML",
          "CSS",
          "Bootstrap",
          "Azure",
          "AWS (S3, SES, Cognito, Cloudwatch, Lambda)",
        ],
      },
      {
        title: "Full Stack Developer - Spacer",
        company: "Undisclosed",
        projectTitle: "Duration: 7 Months",
        achievements: [
          "Developed a corporate office space planning tool to forecast space needs based on location and occupancy.",
          "Built and integrated backend APIs using Nest.js, Express.js, and CouchDB.",
          "Managed AWS services (S3, Cognito, Lambda) and deployment using CloudFormation.",
        ],
        technologies: ["React.js", "Node.js", "Express.js", "CouchDB", "AWS"],
      },
      {
        title: "Full Stack Developer - StoreOps",
        company: "Undisclosed",
        projectTitle: "Duration: 8 Months",
        achievements: [
          "Developed an online shopping platform for luxury men’s fashion with custom designer clothing.",
          "Designed functionality based on business requirements and performed unit testing.",
          "Participated in client meetings and generated daily/weekly status reports.",
        ],
        technologies: ["React.js", "Node.js", "PostgreSQL"],
      },
      {
        title: "Full Stack Developer - Netowrked",
        company: "Undisclosed",
        projectTitle: "Duration: 6 Months",
        achievements: [
          "Developed a LinkedIn-like platform for online community engagement in the US and UK.",
          "Built the complete UI using React and Redux, and integrated APIs with Nest.js and Node.js.",
        ],
        technologies: ["React", "Redux", "Node.js", "TypeScript", "Nest.js"],
      },
      {
        title: "Full Stack Developer - RateEstate",
        company: "Undisclosed",
        projectTitle: "Duration: 1 Year",
        achievements: [
          "Designed and developed web pages for a real estate-related application.",
          "Created tools like web-magnifier and line reader to enhance user experience.",
        ],
        technologies: ["Node.js", "React.js", "MySQL"],
      },
      {
        title: "Full Stack Developer - Hireground",
        company: "Undisclosed",
        projectTitle: "Past Project",
        achievements: [
          "Developed a web-based application for managing buyer-supplier interactions and business opportunities.",
          "Utilized Angular 12 and TypeScript for frontend development and Node.js for backend.",
        ],
        technologies: ["Angular 12", "TypeScript", "Node.js"],
      },
      {
        title: "Full Stack Developer - DPR Construction",
        company: "Undisclosed",
        projectTitle: "Past Project",
        achievements: [
          "Built an administrator MVP web application to track workers at various sites using MQTT server and devices.",
          "Developed the application using Angular 11.",
        ],
        technologies: ["Angular 11"],
      },
    ],
    education: [
      {
        degree: "B.E. - Computer Engineering",
        description: "Gujarat Technological University (GTU), 7.15 SGPA.",
      },
      {
        degree: "H.S.C.",
        description:
          "Gujarat Higher Secondary Education Board (GHSEB), 80.33%.",
      },
      {
        degree: "S.S.C.",
        description: "Gujarat Secondary Education Board (GHSEB), 87.07%.",
      },
    ],
  },
];
